pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "AR-GunMan-Android"
include ':app', ':unityLibrary', 'unityLibrary:xrmanifest.androidlib'
include ':domain'
include ':deviceInterface'
include ':data'
include ':infrastructure'
